name: CI React

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci
        working-directory: ./web-app

      - name: Rodar testes
        run: npm test 
        working-directory: ./web-app

      - name: Rodar build
        run: npm run build
        working-directory: ./web-app